### ISSUE TITLE
Add validation on set keepTtl properties

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-redis#104]
You can use this option to set a key without affecting the ttl already define: 
```yaml 
options: 
  keepTtl: true 
```

You can use this options to set a ttl on key:
```yaml
options: 
  expirationDuration: PT10S 
```

But specifying both are invalid for redis, since redis will never be able to know if we need to keep the tll or set a new one: 
```yaml
options: 
  keepTtl: true 
  expirationDuration: PT10S 
```

We need to add a validation rules to prevent using `keepTtl` with an expiration
