### ISSUE TITLE
Cannot pass a list to the ListPush task from inputs or previous task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-redis#26]
### Expected Behavior

it might be that I'm doing something wrong here, but I want to store a list of strings in Redis for a given key. 

When I do it this way, everything works fine:

```yaml
id: redisKV
namespace: dev

tasks:
  - id: pushListPlugins
    type: io.kestra.plugin.redis.ListPush
    url: redis://host.docker.internal:6379/0
    key: favoritePlugins
    from:
      - redis
      - dbt
      - duckdb
```

![image](https://github.com/kestra-io/plugin-redis/assets/86264395/6b0986bf-9bc6-42f6-b4eb-18bc1d7beeb8)

But passing it from other task or inputs doesn't work - I don't know how to convert that string to an actual list for the ListPush task: 

```yaml
id: cannotExpandTheList
namespace: dev

inputs:
  - name: values
    type: JSON
    defaults: |
      [
        {"dbt": ["build", "test", "snapshot"]},
        {"aws": ["s3", "sqs", "sns", "athena"]},
        {"gcp": ["big-query", "gcs", "cloudrun"]}
      ]

tasks:
  - id: foreach
    type: io.kestra.core.tasks.flows.EachParallel
    value: "{{inputs.values}}"
    tasks:
      - id: pushListPlugins
        type: io.kestra.plugin.redis.ListPush
        url: redis://host.docker.internal:6379/0
        serdeType: JSON
        key: "{{json(taskrun.value) | keys | first}}"
        from: "{{ taskrun.value | jq('.[]') | first }}"
```

error: `Illegal character in path at index 0: ["s3","sqs","sns","athena"]`

### Environment Information

- Kestra Version: develop full image
