### ISSUE TITLE
TriggerList keeps triggering new flow even if there is no data in the List

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-redis#30]
### Actual Behaviour

See https://kestra-io.slack.com/archives/C03FQKXRK3K/p1697133478833919

### Environment Information

- Kestra Version: 0.12
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```
id: redis-trigger-test
namespace: dev
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{ trigger.uri }} containing {{ trigger.count }} lines"
triggers:
  - id: redistrigger
    type: io.kestra.plugin.redis.TriggerList
    url: redis://192.168.1.228:6379/0
    key: mytriggerkey
    maxRecords: 2
```

**Comment by anna-geller** [comment]
Reproducer:

first start redis and then add a flow with a trigger

```yaml
id: redis_trigger
namespace: dev

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{ trigger.uri }} containing {{ trigger.count }} lines"

  - id: cat
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - cat {{ trigger.uri }}

triggers:
  - id: redistrigger
    type: io.kestra.plugin.redis.TriggerList
    url: redis://localhost:6379/0
    key: tools
    maxRecords: 1
    interval: PT1S
```

then, add a flow that will add items to the list in Redis:

```yaml
id: redis_list
namespace: blueprint

variables:
  key: tools
  host: redis://localhost:6379/0

tasks:  
  - id: clearListBeforeReload
    type: io.kestra.plugin.redis.ListPop
    url: "{{ vars.host }}"
    key: "{{ vars.key }}"
    maxRecords: 1

  - id: pushListPlugins
    type: io.kestra.plugin.redis.ListPush
    url: "{{ vars.host }}"
    key: "{{ vars.key }}"
    from:
      - redis
      - duckdb
      - gcp
      - aws
```

See video showing how kestra triggers executions endlessly: https://share.descript.com/view/h93Zh3nfkVE
