### ISSUE TITLE
Redis ListPop task output uri does not contain data

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-redis#48]
### Expected Behavior

On running Redis ListPop task, the data should be popped, and the output uri should contain the popped data. 

### Actual Behaviour

On running Redis ListPop task, the data gets popped. In the Outputs tab, the count of data popped is correctly reflected. The Outputs also contain uri but the file is empty. I verified that the file is empty based on size and its preview content.
![Screenshot 2024-03-23 at 6 30 44 PM](https://github.com/kestra-io/plugin-redis/assets/6594483/0fe023d6-ca7f-4eac-b92e-d8c7385637f3)

![Screenshot 2024-03-23 at 6 30 55 PM](https://github.com/kestra-io/plugin-redis/assets/6594483/44666dfe-a6bf-4967-8783-e9d9ec7f608a)

### Steps To Reproduce

1. Execute the ListPush example flow that pushes data into the list.
2. Execute the ListPop example flow to pop the data.
3. Check the output of the flow containing ListPop task.

### Environment Information

- Kestra Version: 0.15.5
- Plugin version: 0.15.5
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

ListPush flow:

```yaml
id: redis-list-push
namespace: dev
tasks:
  - id: "list_push"
    type: "io.kestra.plugin.redis.ListPush"
    url: redis://:redis@<ip-address>:6379/0
    key: mykey
    from:
       - value1
       - value2
```

ListPop flow
```yaml
id: redis-list-pop
namespace: dev
tasks:
  - id: "list_pop"
    type: "io.kestra.plugin.redis.ListPop"
    url: redis://:redis@<ip-address>:6379/0
    key: mykey
    serdeType: STRING
    maxRecords: 2
```
