### ISSUE TITLE
Can't get connection to Redis database

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-redis#65]
### Actual Behaviour

I'm using an Upstach deployment that works with basic CLI
`docker run -it redis:alpine redis-cli --tls -u redis://default:cc25e9558cb441ba86c7083aa64d226d@eu1-subtle-fox-38070.upstash.io:38070`

Using Kestra task (tried with Set and Get), I've the following error:

![image](https://github.com/user-attachments/assets/8fe378bb-1c80-4d20-8e80-8c80e508170c)

Here is a simple flow

```yaml
id: upstash_test
namespace: kestra.sandbox

tasks:

  - id: redis
    type: io.kestra.plugin.redis.string.Get
    url: 'redis://default:cc25e9558cb441ba86c7083aa64d226d@eu1-subtle-fox-38070.upstash.io:38070'
    key: test
```

### Environment Information

- Kestra Version: 0.17.12 Enterprise
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):
