### ISSUE TITLE
Setting type JSON sets the key value as STRING

### ISSUE THREAD

**Issue by aj-emerich** [kestra-io/plugin-redis#95]
### Describe the issue

I am getting many unexpected results using the Redis plugin. Since I am not a regular Redis user, most of this could be user error or bad expectations. 

None the less, I can not get a flow to correctly set the value of a key as JSON in Redis. It always inserts as a STRING. I am using the following flow:

```
id: redis_set_json
namespace: company.team

tasks:
  - id: set
    type: io.kestra.plugin.redis.string.Set
    url: "{{ secret('REDIS_URI')}}"
    key: "key_json_{{ execution.id }}"
    value: |
      {{ {
        "flow": flow.id,
        "namespace": flow.namespace
      } | toJson }}
    serdeType: JSON

  - id: get
    type: io.kestra.plugin.redis.string.Get
    url: "{{ secret('REDIS_URI')}}"
    serdeType: JSON
    key: "key_json_{{ execution.id }}"
```

In Redis Insights, the value is always `STRING`. The flow works and outputs correctly, as far as I can tell, but it doesn't communicate the set type correctly to Redis.

<img width="708" alt="Image" src="https://github.com/user-attachments/assets/61db534e-b5f6-4946-8f20-5eaa8c06b284" />

Additionally, when manually setting a `JSON` value key in Redis, I get an error when trying to get that value with the following flow:

```
id: redis_get
namespace: ajdev

tasks:
  - id: get
    type: io.kestra.plugin.redis.string.Get
    url: "{{ secret('REDIS_URI')}}"
    key: "get_test"
    serdeType: JSON # Can comment this out, and it'll work for any STRING key.
```

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/00ee4625-05e6-4029-8988-60da43794257" />

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/cd34a326-5530-489b-9ff8-cf8d2403a2a2" />

Lastly, the `serdeType` says it is required but does not need to be used in the GET task. Without specifying the property in Kestra, the flow works whenever the Key in Redis is a `STRING `type, but it gets the same above error if I try to run not using `serdeType` for a `JSON` key.

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/c7171bb5-c5b0-4fa0-90d8-f752d47abf55" />

### Environment

- Kestra Version: develop
