### ISSUE TITLE
Allow expiration fields in Set task to be dynamic

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-redis#99]
### Feature description

Setting expirationDuration in Redis.Set is static, could this be made dynamic?

```
id: valkey_example
namespace: solutions.demo

inputs:
  - id: ttl
    type: STRING
    defaults: "PT1M"

tasks:
  - id: valkey_set_static
    type: io.kestra.plugin.redis.string.Set
    url: "{{secret('valkey-connection-string')}}"
    key: myttlkey
    value: zzzzzzz
    options:
      expirationDuration: "PT1M"

  - id: valkey_set_dyn
    type: io.kestra.plugin.redis.string.Set
    url: "{{secret('valkey-connection-string')}}"
    key: myttlkey_2
    value: aaaaa
    options:
      expirationDuration: "{{inputs.ttl}}"
```
